In [324]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [325]:
data = pd.read_csv('/home/xlify/Downloads/DelayedFlights.csv')
data

Unnamed: 0  Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime   
0                 0  2008      1           3          4   2003.0        1955  \
1                 1  2008      1           3          4    754.0         735   
2                 2  2008      1           3          4    628.0         620   
3                 4  2008      1           3          4   1829.0        1755   
4                 5  2008      1           3          4   1940.0        1915   
...             ...   ...    ...         ...        ...      ...         ...   
1936753     7009710  2008     12          13          6   1250.0        1220   
1936754     7009717  2008     12          13          6    657.0         600   
1936755     7009718  2008     12          13          6   1007.0         847   
1936756     7009726  2008     12          13          6   1251.0        1240   
1936757     7009727  2008     12          13          6   1110.0        1103   

         ArrTime  CRSArrTime UniqueCarrier  ...  TaxiIn TaxiOut  Cancelled   
0         2211.0        2225            WN  ...     4.0     8.0          0  \
1         1002.0        1000            WN  ...     5.0    10.0          0   
2          804.0         750            WN  ...     3.0    17.0          0   
3         1959.0        1925            WN  ...     3.0    10.0          0   
4         2121.0        2110            WN  ...     4.0    10.0          0   
...          ...         ...           ...  ...     ...     ...        ...   
1936753   1617.0        1552            DL  ...     9.0    18.0          0   
1936754    904.0         749            DL  ...    15.0    34.0          0   
1936755   1149.0        1010            DL  ...     8.0    32.0          0   
1936756   1446.0        1437            DL  ...    13.0    13.0          0   
1936757   1413.0        1418            DL  ...     8.0    11.0          0   

         CancellationCode  Diverted  CarrierDelay  WeatherDelay NASDelay   
0                       N         0           NaN           NaN      NaN  \
1                       N         0           NaN           NaN      NaN   
2                       N         0           NaN           NaN      NaN   
3                       N         0           2.0           0.0      0.0   
4                       N         0           NaN           NaN      NaN   
...                   ...       ...           ...           ...      ...   
1936753                 N         0           3.0           0.0      0.0   
1936754                 N         0           0.0          57.0     18.0   
1936755                 N         0           1.0           0.0     19.0   
1936756                 N         0           NaN           NaN      NaN   
1936757                 N         0           NaN           NaN      NaN   

        SecurityDelay  LateAircraftDelay  
0                 NaN                NaN  
1                 NaN                NaN  
2                 NaN                NaN  
3                 0.0               32.0  
4                 NaN                NaN  
...               ...                ...  
1936753           0.0               22.0  
1936754           0.0                0.0  
1936755           0.0               79.0  
1936756           NaN                NaN  
1936757           NaN                NaN  

[1936758 rows x 30 columns]

In [326]:
data.columns

Index(['Unnamed: 0', 'Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime',
       'CRSDepTime', 'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum',
       'TailNum', 'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')

In [327]:
data.drop(['Year','Month','DepTime', 'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay','Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay','Origin', 'Dest','TaxiIn', 'TaxiOut'], axis=1, inplace=True)


In [328]:
data['FlightNum'].count()

1936758

In [329]:
data.drop(['ActualElapsedTime', 'CRSElapsedTime', 'AirTime',], axis=1, inplace=True)

In [330]:
data.columns

Index(['Unnamed: 0', 'DayofMonth', 'DayOfWeek', 'CRSDepTime', 'ArrTime',
       'CRSArrTime', 'UniqueCarrier', 'FlightNum', 'TailNum', 'ArrDelay',
       'DepDelay', 'Distance'],
      dtype='object')

In [331]:
data.drop(['CRSDepTime', 'CRSArrTime', 'UniqueCarrier','TailNum'], axis=1, inplace=True)

In [332]:
data.columns

Index(['Unnamed: 0', 'DayofMonth', 'DayOfWeek', 'ArrTime', 'FlightNum',
       'ArrDelay', 'DepDelay', 'Distance'],
      dtype='object')

In [333]:
data.drop(['Unnamed: 0'], axis=1, inplace=True)

In [334]:
data.columns


Index(['DayofMonth', 'DayOfWeek', 'ArrTime', 'FlightNum', 'ArrDelay',
       'DepDelay', 'Distance'],
      dtype='object')

In [335]:
data.isnull().sum()

DayofMonth       0
DayOfWeek        0
ArrTime       7110
FlightNum        0
ArrDelay      8387
DepDelay         0
Distance         0
dtype: int64

In [336]:
data = data.dropna(subset=['ArrDelay'])

In [337]:
data.head()

DayofMonth  DayOfWeek  ArrTime  FlightNum  ArrDelay  DepDelay  Distance
0           3          4   2211.0        335     -14.0       8.0       810
1           3          4   1002.0       3231       2.0      19.0       810
2           3          4    804.0        448      14.0       8.0       515
3           3          4   1959.0       3920      34.0      34.0       515
4           3          4   2121.0        378      11.0      25.0       688

In [338]:
data.describe()

DayofMonth     DayOfWeek       ArrTime     FlightNum      ArrDelay   
count  1.928371e+06  1.928371e+06  1.928371e+06  1.928371e+06  1.928371e+06  \
mean   1.575206e+01  3.984999e+00  1.610242e+03  2.184296e+03  4.219988e+01   
std    8.776566e+00  1.996050e+00  5.480009e+02  1.944450e+03  5.678472e+01   
min    1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00 -1.090000e+02   
25%    8.000000e+00  2.000000e+00  1.316000e+03  6.110000e+02  9.000000e+00   
50%    1.600000e+01  4.000000e+00  1.715000e+03  1.543000e+03  2.400000e+01   
75%    2.300000e+01  6.000000e+00  2.030000e+03  3.423000e+03  5.600000e+01   
max    3.100000e+01  7.000000e+00  2.400000e+03  9.741000e+03  2.461000e+03   

           DepDelay      Distance  
count  1.928371e+06  1.928371e+06  
mean   4.309169e+01  7.649486e+02  
std    5.326600e+01  5.738858e+02  
min    6.000000e+00  1.100000e+01  
25%    1.200000e+01  3.380000e+02  
50%    2.400000e+01  6.060000e+02  
75%    5.300000e+01  9.970000e+02  
max    2.467000e+03  4.962000e+03

In [339]:
n = 1000000  # Specify the number of rows to drop
data = data.drop(data.index[:n])

In [340]:
def categorize_distance(distance):
    if distance < 600:
        return 'SHORT'
    elif distance <= 2400:
        return 'MEDIUM'
    else:
        return 'LONG'

# Apply the function to the 'distance' column and create a new column 'DistanceCategory'
data['DistanceCategory'] = data['Distance'].apply(categorize_distance)

In [341]:
data['Distance'] =data["DistanceCategory"]

In [342]:
data.drop(['DistanceCategory'], axis=1, inplace=True)

In [343]:
data.drop(['ArrTime'], axis=1, inplace=True)

In [344]:
data.drop(['FlightNum'], axis=1, inplace=True)

In [345]:
mapping = {'SHORT': 1, 'MEDIUM': 2, 'LONG': 3}

# Replace the category labels with numerical values
data['Distance'] = data['Distance'].replace(mapping)

In [346]:
data.head()

DayofMonth  DayOfWeek  ArrDelay  DepDelay  Distance
1003621          22          7     210.0     236.0         1
1003622          22          7     158.0     160.0         1
1003623          22          7     182.0     140.0         2
1003624          22          7       8.0      17.0         2
1003625          22          7      30.0      34.0         2

In [347]:
Y = data['ArrDelay'].values
X = data.drop(['ArrDelay'], axis=1).values

In [348]:
X

array([[ 22.,   7., 236.,   1.],
       [ 22.,   7., 160.,   1.],
       [ 22.,   7., 140.,   2.],
       ...,
       [ 13.,   6.,  80.,   2.],
       [ 13.,   6.,  11.,   1.],
       [ 13.,   6.,   7.,   2.]])

In [349]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [350]:
X_test

array([[ 6.,  4., 18.,  1.],
       [15.,  6., 69.,  2.],
       [12.,  7., 10.,  1.],
       ...,
       [11.,  6., 26.,  1.],
       [26.,  5., 82.,  1.],
       [11.,  5., 22.,  1.]])

In [351]:
Y_test 

array([21., 68., 14., ..., 33., 91., 40.])

In [352]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
linear_reg = LinearRegression()

# Fit the model on the training data
linear_reg.fit(X_train, Y_train)

# Predict on the testing data
y_pred = linear_reg.predict(X_test)

# Calculate evaluation metrics
mse = mean_squared_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)

# Print the evaluation metrics
print("Mean Squared Error:", mse)
print("R-squared:", r2)

Mean Squared Error: 314.5121496455541
R-squared: 0.9070407301873978


In [353]:
np.set_printoptions(suppress=True)
print(X_test[0])

[ 6.  4. 18.  1.]


In [354]:
tmp_dict = {
    "DayofMonth": [4],
    "DayOfWeek": [1] , 
    "DepDelay": [-3],
    "Distance": [1],
              
}
new_data_array = np.array([value[0] for value in tmp_dict.values()])
print(new_data_array)

predictions = linear_reg.predict(new_data_array.reshape(1,-1))

# Print the predictions
print("moselm zabour")
print(predictions)

[ 4  1 -3  1]
moselm zabour
[-3.93542549]


In [355]:
import joblib
joblib.dump(linear_reg, 'linear_reg_model.pkl')

['linear_reg_model.pkl']